name = "endeavour-worker-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[vars]
PORT = "4000"
CLOUDINARY_CLOUD_NAME = ""
CLOUDINARY_API_KEY = ""
CLOUDINARY_API_SECRET = ""

FIREBASE_PROJECT_ID = ""
FIREBASE_CLIENT_EMAIL = ""
FIREBASE_PRIVATE_KEY = ""

GOOGLE_SCRIPT_URL = ""
RECOVERY_GOOGLE_SCRIPT_URL = ""

GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
GOOGLE_REFRESH_TOKEN = ""
GMAIL_USER = ""
EMAIL_FROM = ""

SMTP_MICROSERVICE_URL = ""
MICROSERVICE_SECRET = ""

ADMIN_EMAIL = ""
ADMIN_PASSWORD = ""
JWT_SECRET = ""
FRONTEND_URL = ""
